<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GestionMedicos.aspx.cs" Inherits="Vistas.MenuMedicos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style2 {
            width: 224px;
            margin-left: 200px;
        }
        .auto-style3 {
            width: 224px;
            font-size: xx-large;
        }
        .auto-style4 {
            width: 224px;
            font-size: large;
        }
        .auto-style10 {
            height: 32px;
            width: 271px;
        }
        .auto-style8 {
            height: 32px;
            width: 272px;
        }
        .auto-style1 {
            width: 1219px;
        }
        .auto-style11 {
            width: 197px;
        }
        .auto-style15 {
            height: 32px;
            width: 197px;
        }
        .auto-style18 {
            width: 271px;
        }
        .auto-style19 {
            width: 272px;
        }
        .auto-style20 {
            width: 224px;
            height: 26px;
        }
        .auto-style21 {
            width: 197px;
            height: 26px;
        }
        .auto-style22 {
            width: 143px;
            height: 26px;
        }
        .auto-style23 {
            width: 143px;
        }
        .auto-style24 {
            height: 32px;
            width: 143px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <table class="auto-style1">
            <tr>
                <td class="auto-style2" colspan="7">
                    <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/MenuAdmin.aspx">&lt;&lt;Volver al menu principal</asp:HyperLink>
                </td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">Usuario:
                    <asp:Label ID="lbl_sessionUser" runat="server"></asp:Label>
                </td>
            </tr>
            <tr>
                <td class="auto-style3" colspan="7"><strong>Menu Medicos</strong></td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="7">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="7">
                    <asp:GridView ID="gvMedicos" runat="server" AllowPaging="True" AutoGenerateColumns="False" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical" Height="94px" PageSize="6" Width="717px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="gvMedicos_RowDeleting" OnRowCancelingEdit="gvMedicos_RowCancelingEdit" OnRowEditing="gvMedicos_RowEditing" OnRowUpdating="gvMedicos_RowUpdating" OnPageIndexChanging="gvMedicos_PageIndexChanging" >
                        <AlternatingRowStyle BackColor="Gainsboro" />
                        <Columns>
                            <asp:TemplateField HeaderText="LEGAJO">
                                <EditItemTemplate>
                                    <asp:Label ID="lbl_eit_legajo" runat="server" Text='<%# Bind("Legajo") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblLegajo" runat="server" Text='<%# Bind("Legajo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="DNI">
                                <EditItemTemplate>
                                    <asp:Label ID="lbl_eit_dni" runat="server" Text='<%# Bind("dni_medico") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="dniPaciente" runat="server" Text='<%# Bind("dni_medico") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="NOMBRE COMPLETO">
                                <EditItemTemplate>
                                    <asp:TextBox ID="tb_eit_nombreCompleto" runat="server" Text='<%# (Eval("Nombre")?.ToString().Trim() ?? "") + " " + (Eval("Apellido")?.ToString().Trim() ?? "") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="nombreCompleto" runat="server" Text='<%# Eval("Nombre") + " " + Eval("Apellido") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="SEXO">
                                <EditItemTemplate>
                                    <asp:Label ID="Sexo" runat="server" Text='<%# Bind("Sexo") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Sexo" runat="server" Text='<%# Bind("Sexo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="NACIONALIDAD">
                                <EditItemTemplate>
                                    <asp:TextBox ID="tb_eit_Nacionalidad" runat="server" Text='<%# Bind("Nacionalidad") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Pais" runat="server" Text='<%# Bind("Nacionalidad") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="FECHA DE NACIMIENTO">
                                <EditItemTemplate>
                                    <asp:TextBox ID="tb_eit_fechaNacimiento" runat="server" TextMode="Date" Text='<%# Bind("Fecha_Nacimiento", "{0:yyyy-MM-dd}") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="fechaNacimiento" runat="server" Text='<%# Eval("Fecha_Nacimiento", "{0:dd/MM/yyyy}") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="TELEFONO">
                                <EditItemTemplate>
                                    <asp:TextBox ID="tb_eit_telefono" runat="server" Text='<%# Bind("Telefono") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="telefono" runat="server" Text='<%# Bind("Telefono") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="ESPECIALIDAD">
                                <ItemTemplate>
                                    <asp:Label ID="lblEspecialidad" runat="server" Text='<%# Eval("Especialidad") %>'></asp:Label>
                                </ItemTemplate>
                                 <EditItemTemplate>
                                            <asp:DropDownList ID="ddlEspecialidad" runat="server" 
                                                 DataSourceID="sdsEspecialidades"
                                                 DataTextField="Descripcion" 
                                                 DataValueField="Id_Especialidad"
                                                 SelectedValue='<%# Bind("IdEspecialidad") %>'>
                                             </asp:DropDownList>
                                     </EditItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                        <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                        <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#0000A9" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#000065" />
                    </asp:GridView>
                    <%--<asp:SqlDataSource ID="sdsEspecialidades" runat="server"
                         ConnectionString="Data Source=DESKTOP-CHHDRK8\SQLEXPRESS06;Initial Catalog=Clinica;Integrated Security=True;TrustServerCertificate=True"
                        SelectCommand="SELECT Id_Especialidad, Descripcion FROM Especialidades ORDER BY Descripcion" >
                        </asp:SqlDataSource>--%>
                    <asp:SqlDataSource ID="sdsEspecialidades" runat="server"
     ConnectionString="Data Source=localhost\sqlexpress;Initial Catalog=Clinica;Integrated Security=True;TrustServerCertificate=True"
    SelectCommand="SELECT Id_Especialidad, Descripcion FROM Especialidades ORDER BY Descripcion" >
    </asp:SqlDataSource>
                </td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="7">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style4" colspan="7"><strong>Alta Medico</strong></td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="7">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="2">Ingrese Nombre de Usuario:</td>
                <td class="auto-style23" colspan="3">
                    <asp:TextBox ID="tb_user" runat="server" Width="154px"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="tb_user" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2">*</asp:RequiredFieldValidator>
                </td>
                <td class="auto-style2" colspan="2">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="2">Ingrese Contraseña:</td>
                <td class="auto-style23" colspan="3">
                    <asp:TextBox ID="tb_contra" runat="server" Width="154px" TextMode="Password"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="tb_contra" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2">*</asp:RequiredFieldValidator>
                </td>
                <td class="auto-style2" colspan="2">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style20" colspan="2">Confirmar Contraseña:</td>
                <td class="auto-style22" colspan="3">
                    <asp:TextBox ID="tb_confirmarContra" runat="server" Width="154px" TextMode="Password"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="tb_confirmarContra" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2">*</asp:RequiredFieldValidator>
                </td>
                <td class="auto-style20" colspan="2"></td>
                <td class="auto-style21"></td>
                <td class="auto-style21"></td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="7">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style18" colspan="2">DNI: </td>
                <td class="auto-style23" colspan="3">
                    <asp:TextBox ID="tb_dni" runat="server" ValidationGroup="vg2"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="rfvDni" runat="server" ControlToValidate="tb_dni" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2">*</asp:RequiredFieldValidator>
                </td>
                <td class="auto-style19" colspan="2">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style18" colspan="2">Nombre: </td>
                <td class="auto-style23" colspan="3">
                    <asp:TextBox ID="tb_nombre" runat="server" ValidationGroup="vg2"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="rfvNombre" runat="server" ControlToValidate="tb_nombre" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2">*</asp:RequiredFieldValidator>
                </td>
                <td class="auto-style19" colspan="2">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style18" colspan="2">Apellido: </td>
                <td class="auto-style23" colspan="3">
                    <asp:TextBox ID="tb_apellido" runat="server" ValidationGroup="vg2"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="rfvApellido" runat="server" ControlToValidate="tb_apellido" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2">*</asp:RequiredFieldValidator>
                </td>
                <td class="auto-style19" colspan="2">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style18" colspan="2">Sexo: </td>
                <td class="auto-style23" colspan="3">
                    <asp:DropDownList ID="ddlSexo" runat="server" ValidationGroup="vg2">
                        <asp:ListItem>Masculino</asp:ListItem>
                        <asp:ListItem>Femenino</asp:ListItem>
                    </asp:DropDownList>
                    <asp:RequiredFieldValidator ID="rfvSexo" runat="server" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2" ControlToValidate="ddlSexo">*</asp:RequiredFieldValidator>
                </td>
                <td class="auto-style19" colspan="2">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style18" colspan="2">Nacionalidad:</td>
                <td class="auto-style23" colspan="3">
                    <asp:TextBox ID="tb_Nacionalidad" runat="server" ValidationGroup="vg2"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="rfvNacionalidad" runat="server" ControlToValidate="tb_Nacionalidad" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2">*</asp:RequiredFieldValidator>
                </td>
                <td class="auto-style19" colspan="2">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style10" colspan="2">Fecha de nacimiento:&nbsp; </td>
                <td class="auto-style24" colspan="3">
                    <asp:TextBox ID="tb_fechaNacimiento" runat="server" TextMode="Date" ValidationGroup="vg2"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="rfvFechaNacimiento" runat="server" ControlToValidate="tb_fechaNacimiento" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2">*</asp:RequiredFieldValidator>
                </td>
                <td class="auto-style8" colspan="2">&nbsp;</td>
                <td class="auto-style15"></td>
                <td class="auto-style15"></td>
            </tr>
            <tr>
                <td class="auto-style18" colspan="2">Telefono:</td>
                <td class="auto-style23" colspan="3">
                    <asp:TextBox ID="tb_telefono" runat="server" ValidationGroup="vg2"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="rfvTelefono" runat="server" ControlToValidate="tb_telefono" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2">*</asp:RequiredFieldValidator>
                </td>
                <td class="auto-style19" colspan="2">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="2">Especialidad:</td>
                <td class="auto-style23" colspan="3">
                    <asp:DropDownList ID="ddlEspecialidades" runat="server" Height="16px" Width="137px" DataSourceID="SqlDataSource1" DataTextField="Descripcion" DataValueField="Id_Especialidad" AppendDataBoundItems="true" ValidationGroup="vg2">
                    </asp:DropDownList>
                    <asp:RequiredFieldValidator ID="rfvEspecialidad" runat="server" ErrorMessage="RequiredFieldValidator" ForeColor="Red" ValidationGroup="vg2" ControlToValidate="ddlEspecialidades">*</asp:RequiredFieldValidator>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=localhost\sqlexpress;Initial Catalog=Clinica;Integrated Security=True;Encrypt=True;TrustServerCertificate=True" ProviderName="System.Data.SqlClient" SelectCommand="SELECT [Id_Especialidad], [Descripcion] FROM [Especialidades]"
                                        EnableCaching="true" ></asp:SqlDataSource>
                </td>
                <td class="auto-style2" colspan="2">
                    <asp:Label ID="Label1" runat="server"></asp:Label>
                </td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="2">&nbsp;</td>
                <td class="auto-style23" colspan="3">
                    &nbsp;</td>
                <td class="auto-style2" colspan="2">
                    &nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="2">Horarios de atencion:</td>
                <td class="auto-style23" colspan="3">
                    &nbsp;</td>
                <td class="auto-style2" colspan="2">
                    &nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="2">
                    <asp:GridView ID="gvHorarios" runat="server" AutoGenerateColumns="false" ShowHeader="true" ShowHeaderWhenEmpty="true" 
                        ShowFooter="true" OnRowCommand="gvHorarios_RowCommand"
                        EmptyDataText="No hay horarios cargados. Agregue uno abajo.">
            <Columns>
                <asp:TemplateField HeaderText="Día Semana">
                    <ItemTemplate><%# Eval("DiaSemana") %></ItemTemplate>
                    <FooterTemplate>
                        <asp:DropDownList ID="ddlDia" runat="server">
                            <asp:ListItem Value="2">Lunes</asp:ListItem>
                            <asp:ListItem Value="3">Martes</asp:ListItem>
                            <asp:ListItem Value="4">Miercoles</asp:ListItem>
                            <asp:ListItem Value="5">Jueves</asp:ListItem>
                            <asp:ListItem Value="6">Viernes</asp:ListItem>
                            <asp:ListItem Value="7">Sabado</asp:ListItem>
                            <asp:ListItem Value="1">Domingo</asp:ListItem>
                        </asp:DropDownList>
                    </FooterTemplate>
                </asp:TemplateField>
                
                <asp:TemplateField HeaderText="Hora Inicio">
                    <ItemTemplate><%# Eval("HoraInicio") %></ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtInicio" runat="server" TextMode="Time" />
                    </FooterTemplate>
                </asp:TemplateField>
                
                <asp:TemplateField HeaderText="Hora Fin">
                    <ItemTemplate><%# Eval("HoraFin") %></ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtFin" runat="server" TextMode="Time" />
                    </FooterTemplate>
                </asp:TemplateField>
                
                <asp:TemplateField HeaderText="Acciones">
                    <ItemTemplate>
                        <asp:Button ID="btnEliminar" runat="server" CommandName="Eliminar" 
                            CommandArgument='<%# Container.DataItemIndex %>' Text="Eliminar" />
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:Button ID="btnAgregar" runat="server" CommandName="Agregar" Text="Agregar Horario" />
                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
                </td>
                <td class="auto-style23" colspan="3">
                    <asp:Label ID="lblMensaje" runat="server"></asp:Label>
                </td>
                <td class="auto-style2" colspan="2">
                    &nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="2">&nbsp;</td>
                <td class="auto-style23" colspan="3">
                    &nbsp;</td>
                <td class="auto-style2" colspan="2">
                    &nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="7">
                    &nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style2" colspan="2">&nbsp;</td>
                <td class="auto-style2">
                    <asp:Button ID="btn_Alta" runat="server" OnClick="btn_Alta_Click" Text="Dar de Alta" Width="106px" ValidationGroup="vg2" />
                </td>
                <td class="auto-style2" colspan="2">&nbsp;</td>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style11">&nbsp;</td>
            </tr>
        </table>
    </form>
</body>
</html>
